# Generated by Django 4.2.1 on 2023-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
