# Generated by Django 4.2.5 on 2023-10-30 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('deliveryDate', models.DateField(null=True)),
                ('cancelled', models.BooleanField(default=False, null=True)),
                ('paid', models.BooleanField(default=None, null=True)),
                ('faturedPayment', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('totalSaleValue', models.FloatField()),
                ('deliveryFrequency', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePrice', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('salesOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.salesorder')),
            ],
        ),
    ]
