# Generated by Django 4.2.5 on 2023-11-13 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('products', '0001_initial'),
        ('carriers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePrice', models.FloatField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('deliveryDate', models.DateField(null=True)),
                ('cancelled', models.BooleanField(default=False, null=True)),
                ('sending', models.BooleanField(default=False)),
                ('recieved', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=None, null=True)),
                ('faturedPayment', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('totalSaleValue', models.FloatField()),
                ('deliveryFrequency', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costPrice', models.FloatField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('deliveryDate', models.DateField(null=True)),
                ('cancelled', models.BooleanField(default=False, null=True)),
                ('recieved', models.BooleanField(default=False)),
                ('faturedPayment', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('totalCostValue', models.FloatField()),
                ('deliveryFrequency', models.IntegerField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('costPrice', models.FloatField()),
                ('supplierInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.supplierinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='SalesShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateHour', models.DateTimeField()),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.carrier')),
                ('salesOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('salePrice', models.FloatField()),
                ('supplierInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costPrice', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('salesOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.supplierorder')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePrice', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('salesOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.salesorder')),
            ],
        ),
    ]
