# Generated by Django 4.2.5 on 2023-11-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesInvoiceItem',
            new_name='ItemSalesInvoice',
        ),
        migrations.RenameModel(
            old_name='SupplierInvoiceItem',
            new_name='ItemSupplierInvoice',
        ),
    ]
