# Generated by Django 4.2.1 on 2023-09-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_salesorder_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='deliveryDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='faturedPayment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='deliveryFrequency',
            field=models.IntegerField(null=True),
        ),
    ]
