# Generated by Django 4.2.5 on 2023-11-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_salesinvoiceitem_itemsalesinvoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsalesinvoice',
            old_name='supplierInvoice',
            new_name='salesInvoice',
        ),
        migrations.RenameField(
            model_name='itemsupplierorder',
            old_name='salesOrder',
            new_name='supplierOrder',
        ),
    ]
