# Generated by Django 4.2.1 on 2023-09-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_salesorder_deliverydate_salesorder_faturedpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='cancelled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
