# Generated by Django 4.2.5 on 2023-11-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_salesorder_recieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='recieved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
