# Generated by Django 4.2.1 on 2023-09-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_salesorder_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='deliveryFrequency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
