# Generated by Django 4.2.1 on 2023-09-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_salesorder_deliveryfrequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
