# Generated by Django 4.2.5 on 2023-09-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_salesorder_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='paid',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
