# Generated by Django 4.2.1 on 2023-08-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currentStockQuantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
