# Generated by Django 4.2.1 on 2023-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_disponivel_produto_visivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidadeAtualEstoque',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
