# Generated by Django 4.2.1 on 2023-09-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_currentstockquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currentStockQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
