# Generated by Django 4.2.1 on 2023-05-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_produto_quantidadeatualestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidadePorEmbalagem',
            field=models.IntegerField(default=1),
        ),
    ]
