import Head from 'next/head'
import Image from 'next/image'

import { Inter } from 'next/font/google'
import { AuthContext } from '../contexts/authContext'
import Nav from '../components/shared/Nav'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  //const user = useContext(AuthContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav/>
      </main>
    </>
  )
}
