# Generated by Django 4.2.1 on 2023-09-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticket_originalticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='originalTicket',
        ),
    ]
