# Generated by Django 4.2.1 on 2023-09-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_ticket_originalticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
