# Generated by Django 4.2.5 on 2023-10-30 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': 'Já existe um Usuário com este E-Mail.'}, max_length=254, unique=True)),
                ('username', models.CharField(error_messages={'unique': 'Já existe um Usuário com este Username.'}, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um Usuário com este Nome.'}, max_length=255, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('cpf', models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um Usuário com este CPF.'}, max_length=15, null=True, unique=True)),
                ('cnpj', models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um Usuário com este CNPJ.'}, max_length=18, null=True, unique=True)),
                ('address', models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um Usuário com este Endereço.'}, max_length=255, null=True, unique=True)),
                ('authorizeFature', models.BooleanField(blank=True, default=None, null=True)),
                ('canPurchase', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
