# Generated by Django 4.2.1 on 2023-08-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': 'Já existe um Usuário com este Email.'}, max_length=254, unique=True)),
                ('username', models.CharField(error_messages={'unique': 'Já existe um Usuário com este Nome.'}, max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('cpf', models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um Usuário com este CPF.'}, max_length=15, null=True, unique=True)),
                ('cnpj', models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um Usuário com este CNPJ.'}, max_length=18, null=True, unique=True)),
                ('address', models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um Usuário com este Endereço.'}, max_length=255, null=True, unique=True)),
                ('authorizeFature', models.BooleanField(blank=True, default=None, null=True)),
                ('canPurchase', models.BooleanField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
