# Generated by Django 4.2.1 on 2023-09-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um Usuário com este Nome.'}, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Já existe um Usuário com este Username.'}, max_length=255, unique=True),
        ),
    ]
