# Generated by Django 4.2 on 2023-04-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_cnpj_alter_user_cpf_alter_user_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um Usuário com este CNPJ.'}, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um Usuário com este CPF.'}, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='endereco',
            field=models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um Usuário com este Endereço.'}, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Já existe um Usuário com este Nome.'}, max_length=255, unique=True),
        ),
    ]
